### ISSUE TITLE
建议每个模型的gpu kernel binary保存为独立的so

### ISSUE THREAD

**Issue by chillingche** [huawei-noah/bolt#104]
现有策略是按照gpu设备型号为所有的模型整体生成一个binary，这样做的缺陷有：
- GPU kernel binary以及算法选择对用户不透明，用户不知道哪些模型可以用现在的binary去跑；
- 在已有模型的基础上新增模型后，不能增量更新kernel binary，必须为所有模型重新生成binary。

新策略可能带来的问题：
- 按模型独立保存的so size之和可能大于老策略的单个so的size；
- 针对某个具体模型优化CL kernel，代码更新后，可能忘记更新其他模型的binary；
- 线程安全问题：OCL runtime被配置为静态变量，而不同的模型需要加载不同的so.

**Comment by yuxianzhi** [comment]
Bolt为了降低kernel选择的时间，有一个预处理工具，可以为一个kernel或者一些kernel定制化一个so，不知道这个能不能满足你的需求https://huawei-noah.github.io/bolt/docs/REDUCE_GPU_PREPARE_TIME.html
