### ISSUE TITLE
Elewise算子耗时较大

### ISSUE THREAD

**Issue by ThisisBillhe** [huawei-noah/bolt#106]
Bolt开发者你们好！在BNN的reactnet模型上有较多的数据分布偏移操作，对应到转换好的模型后会有很多的elewise操作。这些elewise操作占到了模型总推理时间的一半以上，而且在我试验中不会随着线程数增加而变快（而conv是会变快一些）。希望之后能将elewise操作也能用上并行加速。

**Comment by yuxianzhi** [comment]
你好，对于reactnet不知道是否应用过这个MR的代码https://github.com/liuzechun/ReActNet/pull/13，这个可以融合和简化部分算子

**Comment by ThisisBillhe** [comment]
有用！十分感谢！
