### ISSUE TITLE
android平台编译失败

### ISSUE THREAD

**Issue by likefxz2009** [huawei-noah/bolt#107]
首先已经配置了ANDROID_NDK_ROOT，其次尝试linux和macos交叉编译Android都失败
macos：
![image](https://user-images.githubusercontent.com/19486844/168549901-24911eaf-f2ba-4f8a-ba38-7f9a03a33c26.png)
Linux:
![image](https://user-images.githubusercontent.com/19486844/168550070-0ee9fb12-576b-406c-bf5a-94c084899277.png)

看着都是在编译protobuf的时候失败了

**Comment by likefxz2009** [comment]
更新：macos上编译成功了，原因是少了一句
export PATH=${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/darwin-x86_64/bin:$PATH
还是在Workflow里找到的，感觉可以提示一下啊

**Comment by likefxz2009** [comment]
顺便问一下，我看bolt里面支持了attention算子，但是直接拿transformer的onnx模型转换到bolt仍然是一些零碎的op，请问要如何做才能让他转换成Attention op

**Comment by yuxianzhi** [comment]
Bolt的attention算子是变长的attention mask部分，只有从caffe模型输入的才会有。有一个大算子multiheadattention，是为GPU实现的，目前还未使用。

**Comment by yuxianzhi** [comment]
> 
感谢提醒，出现这个错误原因是macos自带了clang编译器，与android的clang交叉编译器同名，所以在部分地方错误使用macos的clang， https://github.com/huawei-noah/bolt/blob/master/scripts/setup_compiler.sh#L31
已经交换PATH设置顺序，修复

**Comment by yuxianzhi** [comment]
linux的编译错误或许是下载的android编译器问题，可以尝试换用android ndk22

**Comment by likefxz2009** [comment]
> linux的编译错误或许是下载的android编译器问题，可以尝试换用android ndk22

好的，应该是之前下载的ndk不完整
