### ISSUE TITLE
x2bolt转化工具报错

### ISSUE THREAD

**Issue by kuzuodaoqingchen** [huawei-noah/bolt#124]
zx@d-System-Product-Name:~/bolt-master/install_android-aarch64/tools$ ./X2bolt –d /home/zx/dabnn/build-onnx2bnn/tools/ –m birealnet18stem –i FP1
bash: ./X2bolt: cannot execute binary file: Exec format error

主机编译平台  Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-113-generic x86_64)

按照install.sh脚本自动编译的，不知为何导致这个错误，文件有可执行权限。

**Comment by kuzuodaoqingchen** [comment]
zx@d-System-Product-Name:~/bolt-master/install_android-aarch64/examples$ ./benchmark –m /home/zx/bolt-master/kit/assets/ImageClassification/ghostnet_f32.bolt
-bash: ./benchmark: cannot execute binary file: Exec format error
同样报错

**Comment by yuxianzhi** [comment]
your target is android-aarch64, this can only be excuted on android platform. I guess you are runing benchmark and X2bolt on host(linux-x86_64) machine.

**Comment by kuzuodaoqingchen** [comment]
> your target is android-aarch64, this can only be excuted on android platform. I guess you are runing benchmark and X2bolt on host(linux-x86_64) machine.

好的，感谢回复！
