### ISSUE TITLE
Error while cloning tensorflow

### ISSUE THREAD

**Issue by warpuv** [huawei-noah/bolt#13]
Building by command 

> ./install.sh -t 12 -c llvm

 getting this error:

>  * [new tag]               v2.1.0-rc1                             -> v2.1.0-rc1
>  * [new tag]               v2.1.0-rc2                             -> v2.1.0-rc2
>  * [new tag]               v2.2.0-rc0                             -> v2.2.0-rc0
>  * [new tag]               v2.2.0-rc1                             -> v2.2.0-rc1
> From https://github.com/tensorflow/tensorflow
>  * branch                  master     -> FETCH_HEAD
> error: Sparse checkout leaves no entry on working directory

**Comment by zetyquickly** [comment]
NOTE: you should manually move `schema_generated.h` to where the `TFLite_root/include` is pointing
