### ISSUE TITLE
I think it should be version 0.2.0 not 0.3.0 in commit history.

### ISSUE THREAD

**Issue by ItchyHiker** [huawei-noah/bolt#17]
While in release history you refer to it as 0.2.0.
I am confused.

**Comment by jianfeifeng** [comment]
On 5 June, We released boltv0.3.0 indeed. And We have updated the [release note](https://github.com/huawei-noah/bolt/releases）and the [tag note](https://github.com/huawei-noah/bolt/tags). Sorry for confusing you, and thank you for your reminder.

**Comment by ItchyHiker** [comment]
Thanks.
