### ISSUE TITLE
CMake Error at CMakeLists.txt:25 (install):   install TARGETS given target "test_completeUT" which does not exist.

### ISSUE THREAD

**Issue by Cord3th** [huawei-noah/bolt#2]
Following installation guide in INSTALL.md I face this problem:
`CMake Error at CMakeLists.txt:25 (install):   install TARGETS given target "test_completeUT" which does not exist.`
How can I fix it?

**Comment by jianfeifeng** [comment]
We have updated the INSTALL.md[https://github.com/huawei-noah/bolt/blob/master/INSTALL.md], the latest CMakeLists.txt[https://github.com/huawei-noah/bolt/blob/master/CMakeLists.txt] and  the bolt.cmake[https://github.com/huawei-noah/bolt/blob/master/bolt.cmake] are also provided for you. Please refer to the latest document to compile bolt project again. Thank you!

Best Regards!
The Bolt Team.
