### ISSUE TITLE
bolt交流群加不进去

### ISSUE THREAD

**Issue by MirrorYuChen** [huawei-noah/bolt#4]
bolt交流群不让进吗？

**Comment by jianfeifeng** [comment]
您好，工作日处理加入QQ群的消息较慢，我们已进一步完善QQ群管理机制。请您再次查看是否已经通过申请，如果还未通过申请，请将您的QQ联系方式发送到我的邮箱jianfeifeng@zju.edu.cn, 我会尽快回复您的邮件，感谢您对Bolt框架的关注！

祝好！
