### ISSUE TITLE
What features do you want to add to bolt?

### ISSUE THREAD

**Issue by fengChenHPC** [huawei-noah/bolt#5]
We want to know what you want to add to bolt, we will evaluate your advice and make a plan to develop, so please tell us if your requirement.

- [x]  add an app to demo bolt's ability
- [x]  add supports for mobile GPU
- [x]  add supports for fp32 
- [x] add a benchmark tool
- [ ]  add supports for DaVinci

**Comment by zjd1988** [comment]
@fengChenHPC  你好，后续有支持float32的计划吗？

**Comment by fengChenHPC** [comment]
据我所知，已经有几个人在做这个工作了

**Comment by zjd1988** [comment]
@fengChenHPC  ok，谢谢回复！

**Comment by lijiansong** [comment]
目前只支持armv82?

**Comment by leiwen83** [comment]
Do you have cuda support?

**Comment by fengChenHPC** [comment]
We think Tensorrt has done a good job, so don't want to repeat it. @leiwen83
