### ISSUE TITLE
转换模型失败 Segmentation fault  

### ISSUE THREAD

**Issue by Wanger-SJTU** [huawei-noah/bolt#51]
对于一个较大transformer的模型（200M）。转换时报错Segmentation fault

**Comment by jianfeifeng** [comment]
您好，请问是什么格式模型？如果是onnx, 建议先用onnx-sim进行处理，再尝试转换。我的邮箱是jianfeifeng@outlook.com，如果方便，可以将您的模型发到我的邮箱或者进行更深入的模型细节交流，期待您的来信。
