### ISSUE TITLE
模型名中包含特殊字符时，build_preprocess_ocl.sh失败

### ISSUE THREAD

**Issue by chillingche** [huawei-noah/bolt#53]
普通模型文件中经常包含 ' . ' 等字符，X2bolt转换模型时不会转义这些字符。
然而build_preprocess_ocl.sh把GPU kernel bin导入cpp中编译时，会因为这些特殊字符导致算法文件编译失败。

**Comment by jianfeifeng** [comment]
您好，模型名字在build_preprocess_ocl.sh中会用于新变量名字的定义，没有考虑转义字符的问题会在下一个版本解决。如果您着急使用GPU功能，可以尝试对build_preprocess_ocl.sh中模型名字的转义字符进行处理，或者邮件联系我们，我们会尽快帮您解决这个问题。我的联系邮箱是：jianfeifeng@outlook.com.

祝好！

**Comment by jianfeifeng** [comment]
您好，模型名字会在build_preprocess_ocl.sh中用于新变量名字的定义，没有考虑转义字符的问题会在下一个
