### ISSUE TITLE
支持TorchScript格式的模型做为输入吗 ?

### ISSUE THREAD

**Issue by alphaRGB** [huawei-noah/bolt#59]
REAMDE的介绍上, 从REAMDE文档以及代码目录上来开, PyTorch模型有2种转换方式:
1. PyTorch->ONNX
2. PyTorch->Caffe
这2中方式都有比较大的局限.比如PyTorch->ONNX方式,  PyTorch自身的一些Prim算子(IF, LOOP, LISTUNPACK ... )ONNX支持不好或者不支持.   所以目前的Runtime推理框架是否考虑支持PyTorch Script做为模型的输入格式?   

>https://pytorch.org/docs/stable/jit.html?highlight=script
>https://github.com/pytorch/pytorch/tree/master/torch/csrc/jit

**Comment by jianfeifeng** [comment]
已收到你们提出的需求，后续团队会认真评估并考虑将其纳入开发计划，谢谢。
