### ISSUE TITLE
error adding symbols: file in wrong format

### ISSUE THREAD

**Issue by Cord3th** [huawei-noah/bolt#6]
Hello, compiling with your instructions (using cross compile) I face this problem. How can I solve it?
```
[ 74%] Linking CXX executable ../../../image/bin/test_image_processing
/home/<user>/Downloads/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu/bin/../lib/gcc/aarch64-linux-gnu/8.3.0/../../../../aarch64-linux-gnu/bin/ld: ../../../image/dependency/png/lib/libpng.a(png.o): Relocations in generic ELF (EM: 62)
/home/<user>/Downloads/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu/bin/../lib/gcc/aarch64-linux-gnu/8.3.0/../../../../aarch64-linux-gnu/bin/ld: ../../../image/dependency/png/lib/libpng.a(png.o): Relocations in generic ELF (EM: 62)
/home/<user>/Downloads/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu/bin/../lib/gcc/aarch64-linux-gnu/8.3.0/../../../../aarch64-linux-gnu/bin/ld: ../../../image/dependency/png/lib/libpng.a(png.o): Relocations in generic ELF (EM: 62)
/home/<user>/Downloads/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu/bin/../lib/gcc/aarch64-linux-gnu/8.3.0/../../../../aarch64-linux-gnu/bin/ld: ../../../image/dependency/png/lib/libpng.a: error adding symbols: file in wrong format

```

**Comment by yuxianzhi** [comment]
Please check whether you have used **same** compiler *aarch64-linux-gnu-gcc* to compile *bolt* and *png*. you can use *readelf* tool to check the library.

You need to add following variables before compiling *png*.

```bash
export PATH=<directory to aarch64-linux-gnu-gcc>/bin:$PATH
export CC=aarch64-linux-gnu-gcc
export CXX=aarch64-linux-gnu-g++ 
```

**Comment by Cord3th** [comment]
@yuxianzhi,  thanks for your reply. Recompiled all the libs with _aarch64-linux-gnu-gcc_, but still getting the same error.

**Comment by Cord3th** [comment]
@yuxianzhi nevermind, now I'm getting error:
 `imTrans.c:56:10: fatal error: X11/Xatom.h: No such file or directory
 #include <X11/Xatom.h>
`
and similar. Do I need to link X11 from /usr/include to _aarch64-linux-gnu-gcc_ somehow? By the way, there is no _configure_ file in _libxau_, _libxcb_ and _libx11_, @jianfeifeng, edit build_dependency.sh in bolt/image, please.
