### ISSUE TITLE
[ERROR] thread 0 file C:\Users\Blank\Desktop\bolt-master\model_tools\src\onnx\onnx_adaptee.h line 264 operator name:Less_8 type:Less not supported.

### ISSUE THREAD

**Issue by Blank10492** [huawei-noah/bolt#84]
When I was trying to convert an onnx model of ReActNet to a bolt model, such an error occurred, how can I fix it?

**Comment by yuxianzhi** [comment]
please clone this code and follow this https://github.com/liuzechun/ReActNet/pull/13.

this will simplify onnx graph.

**Comment by Blank10492** [comment]
Thanks, the problem has been solved!
